Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EntityFrameworkServerModeExample

	Partial Public Class EntityInvoice
		Public Property ShipName() As String
		Public Property ShipAddress() As String
		Public Property ShipCity() As String
		Public Property ShipRegion() As String
		Public Property ShipPostalCode() As String
		Public Property ShipCountry() As String
		Public Property CustomerID() As String
		Public Property CustomerName() As String
		Public Property Address() As String
		Public Property City() As String
		Public Property Region() As String
		Public Property PostalCode() As String
		Public Property Country() As String
		Public Property Salesperson() As String
		Public Property OrderID() As Integer
		Public Property OrderDate() As Date?
		Public Property RequiredDate() As Date?
		Public Property ShippedDate() As Date?
		Public Property ShipperName() As String
		Public Property ProductID() As Integer
		Public Property ProductName() As String
		Public Property UnitPrice() As Decimal
		Public Property Quantity() As Short
		Public Property Discount() As Single
		Public Property ExtendedPrice() As Decimal?
		Public Property Freight() As Decimal?
	End Class
End Namespace
